In [ ]:
import torch.nn as nn
import torch
import numpy as np
x=torch.Tensor([[2,7,9,1],[7,1,1,8],[3,7,9,4],[5,0,3,2]])
print(x)
z=torch.ones((4,4))
print(z)
y=torch.mul(x,z)  #对应元素相乘
print(y)

In [ ]:
import torch.nn as nn
import torch
import numpy as np
a=torch.Tensor([[1,2],[3,4]])
b=torch.Tensor([[1,2,3],[3,2,1]])
print(torch.mm(a,b))   #矩阵乘积

In [ ]:
import torch.nn as nn
import torch
import numpy as np
x=torch.Tensor([[2,7,9,1],[7,1,1,8],[3,7,9,4],[5,0,3,2]])
print(x)
print(x.size())
print("---------------------------------------------")
y=x.view(16)
print(y)
print(y.size())
print(x.size())   #原始size并未被改变
print("---------------------------------------------")
z=x.view((8,-1))  #-1代表根据提供的一个维度自己推算
print(z)
print(z.size())

In [ ]:
#1、下面研究一下选取任意行列，并尝试卷积操作，手动/自动
import torch.nn as nn
import torch
import numpy as np
x=torch.Tensor([[2,7,9,1],[7,1,1,8],[3,7,9,4],[5,0,3,2]])
print("x的值：\n",x)
print("---------------------------------------------")
print("x第一个3x3的块：\n",x[0:3,0:3]) #选取第一个3x3的块

print("\n==============================================================================\n")
#手动来一次卷积
print("手动来卷积：")
kernel=torch.Tensor([[1,0,1],[0,1,0],[1,0,1]])
t=x[0:3,0:3]
conv=t.mul(kernel)
print("第一个3x3块进行卷积操作：\n",conv)
print("卷积结果：\n",float(conv.sum()))
print("---------------------------------------------")
t=x[0:3,1:4]
conv=t.mul(kernel)
print("卷积结果：\n",float(conv.sum()))
print("---------------------------------------------")
t=x[1:4,0:3]
conv=t.mul(kernel)
print("卷积结果：\n",float(conv.sum()))
print("---------------------------------------------")
t=x[1:4,1:4]
conv=t.mul(kernel)
print("卷积结果：\n",float(conv.sum()))

print("\n==============================================================================\n")
t=x[0:3,0:3]
conv=t-kernel
conv=torch.abs(conv)
print(-conv.sum())

t=x[0:3,1:4]
conv=t-kernel
conv=torch.abs(conv)
print(-conv.sum())

t=x[1:4,0:3]
conv=t-kernel
conv=torch.abs(conv)
print(-conv.sum())

t=x[1:4,1:4]
conv=t-kernel
conv=torch.abs(conv)
print(-conv.sum())

x的值：
 tensor([[2., 7., 9., 1.],
        [7., 1., 1., 8.],
        [3., 7., 9., 4.],
        [5., 0., 3., 2.]])
---------------------------------------------
x第一个3x3的块：
 tensor([[2., 7., 9.],
        [7., 1., 1.],
        [3., 7., 9.]])


手动来卷积：
第一个3x3块进行卷积操作：
 tensor([[2., 0., 9.],
        [0., 1., 0.],
        [3., 0., 9.]])
卷积结果：
 24.0
---------------------------------------------
卷积结果：
 20.0
---------------------------------------------
卷积结果：
 23.0
---------------------------------------------
卷积结果：
 20.0


tensor(-41.)
tensor(-42.)
tensor(-31.)
tensor(-32.)


In [ ]:
#2、固定卷积核，自动卷积
import torch.nn as nn
import torch
import torch.nn.functional as F
x=torch.Tensor([[2,7,9,1],[7,1,1,8],[3,7,9,4],[5,0,3,2]]).unsqueeze(0).unsqueeze(0)
print("x的值：\n",x)
kernel=torch.Tensor([[1,0,1],[0,1,0],[1,0,1]]).unsqueeze(0).unsqueeze(0)
#因为在实际应用时tensor一般是四维的，所以使用unsqueeze()拓展维度

#想要使用自己的kernel，不能用nn.conv2d，要用F中的
#参考https://blog.csdn.net/u013289254/article/details/103896635
print("\n===============================================================================\n")
print("自动卷积：")
# torch.nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
output=F.conv2d(x,kernel)
print(output)   #发现结果和上面一样

x的值：
 tensor([[[[2., 7., 9., 1.],
          [7., 1., 1., 8.],
          [3., 7., 9., 4.],
          [5., 0., 3., 2.]]]])


自动卷积：
tensor([[[[24., 20.],
          [23., 20.]]]])


In [ ]:
#3、下面尝试使用图片进行卷积，并测试AdderNet()
# 图片的读取参考https://www.cnblogs.com/yinxiangnan-charles/p/5928689.html
# ————————————————————使用PIL————————————————————————
from PIL import Image
im = Image.open('1.jpg')
im.show()

In [ ]:
#——————————————————使用matplotlib————————————————————
import matplotlib.pyplot as plt # plt 用于显示图片
import matplotlib.image as mpimg # mpimg 用于读取图片
import numpy as np
#这种方式图片可以直接显示
air = mpimg.imread('1.jpg') # 读取和代码处于同一目录下的 lena.png
plt.imshow(air)
plt.axis('off')
plt.show()

img=np.array(air)
print(img.shape)

In [ ]:
#——————————————————使用CV——————————————————
import cv2
import numpy as np
imgcv=cv2.imread('1.jpg')
#cv2.imshow('airplane', imgcv)
#调整图片大小
imgcv2 = cv2.resize(imgcv, (256,256), interpolation=cv2.INTER_CUBIC)  
#cv2.imshow('resize',imgcv2)
#转为灰度图
img_gray = cv2.cvtColor(imgcv2,cv2.COLOR_RGB2GRAY)
print(img_gray.shape)
#cv2.imshow('gray',img_gray)
#cv2.waitKey(0)

(256, 256)


In [ ]:
#测试矩阵的可视化，以为后面卷积后特征可视化做准备
import numpy as np
import cv2
#随机生成矩阵，可视化
tst=np.random.randint(0,256,(128,128,3),dtype=np.uint8) #cv支持unit8和float32 
cv2.imshow('tst',tst)
cv2.waitKey(0)

In [ ]:
#4、将上述图片转为tensor
import torch
import torch.nn as nn
import torch.nn.functional as F 
x=torch.Tensor([[2,7,9,1],[7,1,1,8],[3,7,9,4],[5,0,3,2]]).unsqueeze(0).unsqueeze(0)
#img_t=torch.from_numpy(img_gray).unsqueeze(0).unsqueeze(0).float()
#img_t=torch.FloatTensor(img_gray).unsqueeze(0).unsqueeze(0)
print(img_t.size())
#构造两个边缘检测卷积核，sobel
kernel_sobel_x=torch.Tensor([[-1,0,1],[-2,0,2],[-1,0,1]]).unsqueeze(0).unsqueeze(0)
kernel_sobel_y=torch.Tensor([[1,2,1],[0,0,0],[-1,-2,-1]]).unsqueeze(0).unsqueeze(0)
#kernel_sobel_x=kernel_sobel_x.byte()     
#kernel_sobel_y=kernel_sobel_y.byte()                         
output=F.conv2d(img_t,kernel_sobel_x).squeeze(0).squeeze(0)
output=output.numpy()
#cv2.imshow('conv',output)
#cv2.waitKey(0)


torch.Size([1, 1, 256, 256])


In [ ]:
import torch
from torch.nn import functional as f
 
x = torch.arange(0, 1*3*15*15).float()
x = x.view(1,3,15,15)
print(x)
x1 = f.unfold(x, kernel_size=3, dilation=1, stride=1)
print(x1.shape)
B, C_kh_kw, L = x1.size()
x1 = x1.permute(0, 2, 1)
x1 = x1.view(B, L, -1, 3, 3)
print(x1)
 

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
tensor([[[[ 0.,  1.],
          [ 2.,  3.]],

         [[ 4.,  5.],
          [ 6.,  7.]],

         [[ 8.,  9.],
          [10., 11.]]]])


In [ ]:
import torch
from torch.nn import functional as f
x=torch.Tensor([[[1,2,3],[4,5,6]]])
print(x.size())
x=x.permute(2,1,0)
print(x.size())
print(x)

torch.Size([1, 2, 3])
torch.Size([3, 2, 1])
tensor([[[1.],
         [4.]],

        [[2.],
         [5.]],

        [[3.],
         [6.]]])


In [ ]:
! python /content/AdderNet-master/resnet50.py

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): adder2d()
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): adder2d()
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): adder2d()
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): adder2d()
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): Bottleneck(
      (conv1): adder2d()
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, af

In [ ]:
import torch.nn as nn
import torch
import torch.nn.functional as F
x=torch.Tensor([[1,0,0,0,1],[0,2,0,2,0],[0,0,8,0,0],[0,2,0,2,0],[1,0,0,0,1]]).unsqueeze(0).unsqueeze(0)
print("x的值：\n",x)
kernel=torch.Tensor([[0,1,0],[1,-4,1],[0,1,0]]).unsqueeze(0).unsqueeze(0)
#因为在实际应用时tensor一般是四维的，所以使用unsqueeze()拓展维度

#想要使用自己的kernel，不能用nn.conv2d，要用F中的
#参考https://blog.csdn.net/u013289254/article/details/103896635
print("\n===============================================================================\n")
print("自动卷积：")
# torch.nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
output=F.conv2d(x,kernel)
print(output)   #发现结果和上面一样

x的值：
 tensor([[[[1., 0., 0., 0., 1.],
          [0., 2., 0., 2., 0.],
          [0., 0., 8., 0., 0.],
          [0., 2., 0., 2., 0.],
          [1., 0., 0., 0., 1.]]]])


自动卷积：
tensor([[[[ -8.,  12.,  -8.],
          [ 12., -32.,  12.],
          [ -8.,  12.,  -8.]]]])
